### ISSUE TITLE
Pequeños cambios en estilos

### ISSUE THREAD

**Issue by hvarg** [begandroide/INF322#5]
En la siguiente imagen podemos ver dos pequeños problemas:
![Screen Shot 2020-02-19 at 17 53 17](https://user-images.githubusercontent.com/15269912/74875417-f57f6280-5340-11ea-8739-6f5d2ecee037.png)

El primero es que la tab está seleccionada pero el contenido no cambia, en este caso pueden optar por poner contenido dummy o simplemente usar un `disable` en la tab para que no se pueda clickear.

Lo segundo es que cuando ocurre un problema, el error mostrado hace que parte del texto saga fuera de los márgenes del componente.

**Comment by begandroide** [comment]
Se implementan las modificaciones pedidas. Precisamente en el comit [19e9e50](https://github.com/begandroide/INF322/pull/7/commits/19e9e5040d7d8b6e6bbedaf449b93633b8412b2f)
